export const TEACHERS_ADMIN = "/admin/docentes"
export const TEACHER_GAMES = "/docente/juegos"
export const ADMIN_GALLERIES = "/admin/ver-galerias"
export const ADMIN_POSTS = "/admin/ver-posts"
export const TEACHER_REGIST = "/admin/registrar-docentes"
export const CREATE_GALLERIES = "/admin/crear-galeria"
export const CREATE_POST = "/admin/crear-post"