export const HOME = "/"
export const ADMISSIONS = "/admisiones"
export const ABOUT = "/nosotros"
export const METODOLOGY = "/metodologia"
export const GALLERY = "/ver-galerias"
export const CONTACT = "/contactanos"
export const LOGIN = "/iniciarsesion"
export const NOTFOUND = "/*"